services:
  opensearch:
    build: ./opensearch
    container_name: opensearch_hybrid_search
    environment:
      discovery.type: single-node
      node.name: opensearch
      plugins.security.disabled: "true"
      logger.level: info
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: SuperSecretPassword_123
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - opensearch-net

  opensearch_dashboards:
    image: opensearchproject/opensearch-dashboards:2.16.0
    container_name: opensearch_hybrid_search_dashboards
    ports:
      - "5601:5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
    depends_on:
      - opensearch
    networks:
      - opensearch-net

  inference:
    container_name: inference-api
    build:
      context: ./inference_api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OMP_NUM_THREADS=1
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    networks:
      - opensearch-net

networks:
  opensearch-net:
    driver: bridge
